export const Config = {
    POLL_INTERVAL_FAST: Number(process.env.EXPO_PUBLIC_POLL_INTERVAL_FAST) || 1000,
    POLL_INTERVAL_SLOW: Number(process.env.EXPO_PUBLIC_POLL_INTERVAL_SLOW) || 5000,
    VOL_STEP_SMALL: Number(process.env.EXPO_PUBLIC_VOL_STEP_SMALL) || 1,
    VOL_STEP_MEDIUM: Number(process.env.EXPO_PUBLIC_VOL_STEP_MEDIUM) || 5,
    VOL_STEP_LARGE: Number(process.env.EXPO_PUBLIC_VOL_STEP_LARGE) || 10,
    METRO_CHECK_INTERVAL: Number(process.env.EXPO_PUBLIC_METRO_CHECK_INTERVAL) || 5000,
    METRO_CHECK_TIMEOUT: Number(process.env.EXPO_PUBLIC_METRO_CHECK_TIMEOUT) || 4000,
};
